/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layout;

import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import koneksi.New_ConnectDB;
import static layout.MainFrame.mode2;
import static layout.MainFrame.ta_alamat;
import static layout.MainFrame.ta_alamat1;
import static layout.MainFrame.tf_IdCust;
import static layout.MainFrame.tf_IdUser;
import static layout.MainFrame.tf_email1;
import static layout.MainFrame.tf_nama1;
import static layout.MainFrame.tf_namaKaryawan;
import static layout.MainFrame.tf_nohp;
import static layout.MainFrame.tf_nohp1;
import static layout.UserFrame.tabeloutz;

/**
 *
 * @author user
 */
public class CustomersFrame extends javax.swing.JFrame {
    private Connection conn = new New_ConnectDB().connect();
    private DefaultTableModel tabmode;

    /**
     * Creates new form CustomersFrame
     */
    public CustomersFrame() {
        initComponents();
        dataTable();
    }
    
    protected void dataTable() {
        Object[]baris = {"ID Customers","Nama Customers","NO Handphone","Email","Alamat"};
        tabmode = new DefaultTableModel(null, baris);
        tabeloutx.setModel(tabmode);
        String sql = "select * from customers order by Nama asc";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String skode_barang = hasil.getString("ID_Cust");
                String snama_barang = hasil.getString("Nama");
                String sharga_satuan = hasil.getString("No_HP");
                String sjumlah_barang = hasil.getString("Email");
                String salamat = hasil.getString("Alamat");
                String[] data = {skode_barang,snama_barang,sharga_satuan,sjumlah_barang,salamat};
                tabmode.addRow(data);

            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_cari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeloutx = new javax.swing.JTable();
        bg = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Pencarian");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 60, 20));

        tf_cari.setText("ID Customers");
        tf_cari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_cariMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tf_cariMouseExited(evt);
            }
        });
        tf_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_cariActionPerformed(evt);
            }
        });
        getContentPane().add(tf_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 140, -1));

        tabeloutx.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabeloutx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeloutxMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabeloutx);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, 100));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg_customers.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu1.setText("Close");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        dispose();
        mode2.setSelectedItem("[MODE] INPUT CUSTOMERS");
    }//GEN-LAST:event_jMenu1MouseClicked

    private void tf_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_cariActionPerformed
        // TODO add your handling code here:
        Object[]baris = {"ID Customers","Nama Customers","NO Handphone","Email","Alamat"};
        tabmode = new DefaultTableModel(null, baris);
        tabeloutx.setModel(tabmode);
        String sql = "select * from customers where ID_Cust like '%"+tf_cari.getText()+"%'";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String skode_barang = hasil.getString("ID_Cust");
                String snama_barang = hasil.getString("Nama");
                String sharga_satuan = hasil.getString("No_HP");
                String sjumlah_barang = hasil.getString("Email");
                String salamat = hasil.getString("Alamat");
                String[] data = {skode_barang,snama_barang,sharga_satuan,sjumlah_barang,salamat};
                tabmode.addRow(data);

            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tf_cariActionPerformed

    private void tf_cariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_cariMouseClicked
        // TODO add your handling code here:
        tf_cari.setText("");
    }//GEN-LAST:event_tf_cariMouseClicked

    private void tf_cariMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_cariMouseExited
        // TODO add your handling code here
        tf_cari.setText("ID Customers");
    }//GEN-LAST:event_tf_cariMouseExited

    private void tabeloutxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeloutxMouseClicked
        // TODO add your handling code here:
        int bar = tabeloutx.getSelectedRow();
        String a = tabmode.getValueAt (bar, 0).toString();
        String b = tabmode.getValueAt (bar, 1).toString();
        String c = tabmode.getValueAt (bar, 2).toString();
        String d = tabmode.getValueAt (bar, 3).toString();
        String e = tabmode.getValueAt (bar, 4).toString();
        tf_IdCust.setText(a);
        tf_nama1.setText(b);
        tf_nohp1.setText(c);
        tf_email1.setText(d);
        ta_alamat1.setText(e);
    }//GEN-LAST:event_tabeloutxMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomersFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tabeloutx;
    private javax.swing.JTextField tf_cari;
    // End of variables declaration//GEN-END:variables
}
