/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layout;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import koneksi.New_ConnectDB;
import static layout.MainFrame.btn_Data;
import static layout.MainFrame.btn_Pemesanan;
import static layout.MainFrame.btn_Transaksi;

/**
 *
 * @author user
 */
public class LoginFrame_Owner extends javax.swing.JFrame {
    private Connection koneksi;
    private New_ConnectDB conn = new New_ConnectDB();

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame_Owner() {
        initComponents();
        setLocationRelativeTo(this);
        tf_loginUser1.requestFocus();
        setTanggal();
    }
    
    protected void kosong(){
        tf_loginUser1.setText("");
        tf_loginPass.setText("");
    }
    
    public void setTanggal(){
        java.util.Date skrg = new java.util.Date();
        java.text.SimpleDateFormat kal = new
        java.text.SimpleDateFormat("dd/MM/yyyy");
        tf_tanggal.setText(kal.format(skrg));
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        tf_loginUser1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_loginPass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        tf_tanggal = new javax.swing.JTextField();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Username");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 130, 20));

        tf_loginUser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_loginUser1ActionPerformed(evt);
            }
        });
        tf_loginUser1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_loginUser1KeyPressed(evt);
            }
        });
        getContentPane().add(tf_loginUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 210, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 110, 20));

        tf_loginPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_loginPassActionPerformed(evt);
            }
        });
        tf_loginPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_loginPassKeyPressed(evt);
            }
        });
        getContentPane().add(tf_loginPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 210, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 80, 30));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("Home");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 70, 30));

        tf_tanggal.setEditable(false);
        getContentPane().add(tf_tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, 110, 30));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg_login.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_loginUser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_loginUser1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_loginUser1ActionPerformed

    private void tf_loginUser1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_loginUser1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER){
            tf_loginPass.requestFocus();
        }
    }//GEN-LAST:event_tf_loginUser1KeyPressed

    private void tf_loginPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_loginPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_loginPassActionPerformed

    private void tf_loginPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_loginPassKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER){
            conn.connect();
            try {
                String sql = "select * from admin where Username = '" + tf_loginUser1.getText() + "' and Password = '" + tf_loginPass.getText() + "'";
                Statement stat = conn.connect().createStatement();
                ResultSet rsLogin = stat.executeQuery(sql);

                rsLogin.next();
                rsLogin.last(); //mengecek jumlah baris pada hasil query
                if (rsLogin.getRow()==1){
                    JOptionPane.showMessageDialog(null, "Login Berhasil!");
                    dispose();
                    //String snama_verif = rsLogin.getString("nama_karyawan");
                    
                    //MainFrame b= new MainFrame();
                    //b.tf_IdVerif.setText(snama_verif);
                    //b.tf_NamaVerif.setText(asd);
                    //b.setVisible(true);
                    new MainFrame().setVisible(true); //<-- BILA MAU DIARAHKAN KE Frame Menu Utama
                    btn_Data.setEnabled(false);
                    btn_Transaksi.setEnabled(false);
                } else {
                    JOptionPane.showMessageDialog(null, "Maaf, Username / Password anda salah!");
                    //kosong();
                    tf_loginUser1.requestFocus();
                }
            } catch (SQLException e) {
            }
        }
    }//GEN-LAST:event_tf_loginPassKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        conn.connect();
        try {
            String sql = "select * from admin where Username = '" + tf_loginUser1.getText() + "' and Password = '" + tf_loginPass.getText() + "'";
            Statement stat = conn.connect().createStatement();
            ResultSet rsLogin = stat.executeQuery(sql);

            rsLogin.next();
            rsLogin.last(); //mengecek jumlah baris pada hasil query
            if (rsLogin.getRow()==1){
                JOptionPane.showMessageDialog(null, "Login Berhasil!");
                dispose();
                //String snama_verif = rsLogin.getString("nama_karyawan");
                //menu_karyawan b= new menu_karyawan();
                //b.tumbal_verif.setText(snama_verif);
                //b.setVisible(true);
                new MainFrame().setVisible(true); //<-- BILA MAU DIARAHKAN KE Frame Menu Utama
                btn_Data.setEnabled(false);
                btn_Transaksi.setEnabled(false);
                tf_loginUser1.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Maaf, Username / Password anda salah!");
                kosong();
                tf_loginUser1.requestFocus();
            }
        } catch (SQLException e) {
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new PublicFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame_Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame_Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame_Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame_Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame_Owner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField tf_loginPass;
    public static javax.swing.JTextField tf_loginUser1;
    private javax.swing.JTextField tf_tanggal;
    // End of variables declaration//GEN-END:variables
}
